fullnameOverride: cert-manager
global:
  podSecurityPolicy:
    useAppArmor: false
  priorityClassName: system-cluster-critical
installCRDs: true
replicaCount: 1
image:
  pullPolicy: Always
resources:
  requests:
    cpu: 10m
    memory: 32Mi
  limits:
    cpu: 500m
    memory: 512Mi

webhook:
  replicaCount: 1
  image:
    pullPolicy: Always
  resources:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      cpu: 128m
      memory: 256Mi

cainjector:
  replicaCount: 1
  image:
    pullPolicy: Always
  resources:
    requests:
      cpu: 300m
      memory: 500Mi
    limits:
      cpu: 500m
      memory: 1000Mi

startupapicheck:
  image:
    pullPolicy: Always

prometheus:
  enabled: true
ingressShim:
  defaultIssuerName: letsencrypt
  defaultIssuerKind: ClusterIssuer
